[project]
name = "maxpto"
version = "0.1.0"
description = "Maximize your PTO"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "holidays>=0.63",
    "july>=0.1.3",
    "streamlit>=1.41.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.6",
]
